### ISSUE TITLE
Issue at startup

### ISSUE THREAD

**Issue by MTrinkiesJr** [hoohoot/synapse-keycloak-adapter#2]
Hey there I just tried out your adapter in Kubernetes. I configured all env vars and the container is starting a givrs me that issue:

`21-10-2020 10:38:49.417 [main] DEBUG io.netty.util.NetUtil.debug - /proc/sys/net/core/somaxconn: 128
java.lang.ClassNotFoundException: hoohoot.synapse.adapter.server.MainVerticle
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at io.vertx.core.impl.JavaVerticleFactory.createVerticle(JavaVerticleFactory.java:37)
	at io.vertx.core.impl.DeploymentManager.createVerticles(DeploymentManager.java:229)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeployVerticle$2(DeploymentManager.java:202)
	at io.vertx.core.impl.FutureImpl.setHandler(FutureImpl.java:79)
	at io.vertx.core.impl.DeploymentManager.doDeployVerticle(DeploymentManager.java:171)
	at io.vertx.core.impl.DeploymentManager.doDeployVerticle(DeploymentManager.java:143)
	at io.vertx.core.impl.DeploymentManager.deployVerticle(DeploymentManager.java:131)
	at io.vertx.core.impl.VertxImpl.deployVerticle(VertxImpl.java:665)
	at io.vertx.core.impl.launcher.commands.VertxIsolatedDeployer.deploy(VertxIsolatedDeployer.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.vertx.core.impl.launcher.commands.ClasspathHandler.deploy(ClasspathHandler.java:159)
	at io.vertx.core.impl.launcher.commands.RunCommand.deploy(RunCommand.java:397)
	at io.vertx.core.impl.launcher.commands.RunCommand.run(RunCommand.java:270)
	at io.vertx.core.impl.launcher.VertxCommandLauncher.execute(VertxCommandLauncher.java:226)
	at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:380)
	at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:324)
	at io.vertx.core.Launcher.main(Launcher.java:45)
Oct 21, 2020 10:38:49 AM io.vertx.core.impl.launcher.commands.VertxIsolatedDeployer
SEVERE: Failed in deploying verticle
java.lang.ClassNotFoundException: hoohoot.synapse.adapter.server.MainVerticle
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at io.vertx.core.impl.JavaVerticleFactory.createVerticle(JavaVerticleFactory.java:37)
	at io.vertx.core.impl.DeploymentManager.createVerticles(DeploymentManager.java:229)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeployVerticle$2(DeploymentManager.java:202)
	at io.vertx.core.impl.FutureImpl.setHandler(FutureImpl.java:79)
	at io.vertx.core.impl.DeploymentManager.doDeployVerticle(DeploymentManager.java:171)
	at io.vertx.core.impl.DeploymentManager.doDeployVerticle(DeploymentManager.java:143)
	at io.vertx.core.impl.DeploymentManager.deployVerticle(DeploymentManager.java:131)
	at io.vertx.core.impl.VertxImpl.deployVerticle(VertxImpl.java:665)
	at io.vertx.core.impl.launcher.commands.VertxIsolatedDeployer.deploy(VertxIsolatedDeployer.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.vertx.core.impl.launcher.commands.ClasspathHandler.deploy(ClasspathHandler.java:159)
	at io.vertx.core.impl.launcher.commands.RunCommand.deploy(RunCommand.java:397)
	at io.vertx.core.impl.launcher.commands.RunCommand.run(RunCommand.java:270)
	at io.vertx.core.impl.launcher.VertxCommandLauncher.execute(VertxCommandLauncher.java:226)
	at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:380)
	at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:324)
	at io.vertx.core.Launcher.main(Launcher.java:45)
java.lang.ClassNotFoundException: hoohoot.synapse.adapter.server.MainVerticle
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at io.vertx.core.impl.JavaVerticleFactory.createVerticle(JavaVerticleFactory.java:37)
	at io.vertx.core.impl.DeploymentManager.createVerticles(DeploymentManager.java:229)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeployVerticle$2(DeploymentManager.java:202)
	at io.vertx.core.impl.FutureImpl.setHandler(FutureImpl.java:79)
	at io.vertx.core.impl.DeploymentManager.doDeployVerticle(DeploymentManager.java:171)
	at io.vertx.core.impl.DeploymentManager.doDeployVerticle(DeploymentManager.java:143)
	at io.vertx.core.impl.DeploymentManager.deployVerticle(DeploymentManager.java:131)
	at io.vertx.core.impl.VertxImpl.deployVerticle(VertxImpl.java:665)
	at io.vertx.core.impl.launcher.commands.VertxIsolatedDeployer.deploy(VertxIsolatedDeployer.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.vertx.core.impl.launcher.commands.ClasspathHandler.deploy(ClasspathHandler.java:159)
	at io.vertx.core.impl.launcher.commands.RunCommand.deploy(RunCommand.java:397)
	at io.vertx.core.impl.launcher.commands.RunCommand.run(RunCommand.java:270)
	at io.vertx.core.impl.launcher.VertxCommandLauncher.execute(VertxCommandLauncher.java:226)
	at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:380)
	at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:324)
	at io.vertx.core.Launcher.main(Launcher.java:45)`

So I checked out your repo and there seems not to be any "hoohoot.synapse.adapter.server.MainVerticle" class neither the folder "server". Is there any way to fix that or did I do something wrong?

Regards
Michael

**Comment by oknozor** [comment]
Hey @MTrinkiesJr  it's been a while since we last worked on this. I might need to use this really soon and work on this project again (maybe this weekend). I'll let you know when this is fixed.
